### ISSUE TITLE
Organisation level secrets

### ISSUE THREAD

**Issue by bendavies** [webfactory/secret-spreader#4]
Hi,

Now that Organization level secrets are available, I'd still like to manage them with code/configuration.
Do you have any interest in making this or another project to write secrets to the Organziation?

Thanks

**Comment by mpdude** [comment]
To be honest, my team’s needs have been addressed with the availability of organization-level secrets, so I cannot make any promises as to implementing this myself or how swift I can follow up in PRs.

Just to make I fully understand: would you want to manage secrets across several organizations, or does it give you any advantages (which?) to configure secrets via config files?
